shell scripts should fail immediately if any subcommand fails

diff --git a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/create_vcap_user b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/create_vcap_user
--- a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/create_vcap_user
+++ b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/create_vcap_user
@@ -6,6 +6,8 @@
 # Requires:
 # * $ORIGUSER - another local user with authorized_keys for SSH access; will be copied to vcap user
 
+set -e # exit immediately if a simple command exits with a non-zero status
+
 if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root" 1>&2
   exit 1
diff --git a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_base_packages b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_base_packages
--- a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_base_packages
+++ b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_base_packages
@@ -5,6 +5,8 @@ if [[ $EUID -ne 0 ]]; then
   exit 1
 fi
 
+set -e # exit immediately if a simple command exits with a non-zero status
+
 apt-get install python-software-properties
 add-apt-repository ppa:keithw/mosh
 
diff --git a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_bosh_plugins b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_bosh_plugins
--- a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_bosh_plugins
+++ b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/install_bosh_plugins
@@ -5,6 +5,8 @@
 # Options:
 # * $UPGRADE - re-install or upgrade gems if already installed
 
+set -e # exit immediately if a simple command exits with a non-zero status
+
 if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root" 1>&2
   exit 1
diff --git a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/validate_bosh_deployer b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/validate_bosh_deployer
--- a/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/validate_bosh_deployer
+++ b/lib/bosh-bootstrap/stages/stage_prepare_inception_vm/validate_bosh_deployer
@@ -2,6 +2,8 @@
 
 # Validate that BOSH deployer is ready
 
+set -e # exit immediately if a simple command exits with a non-zero status
+
 if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root" 1>&2
   exit 1
